import { Figtree } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import ReduxProvider from "@/redux/provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import QueryProvider from "@/providers/QueryProvider";

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["300","400","500","600","700","800","900"],
  variable: "--font-figtree",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${figtree.className} antialiased`}>
        <ReduxProvider>
          <QueryProvider> 
            <Header />
            {children}
          </QueryProvider>
        </ReduxProvider>
         <ToastContainer
          position="top-right"
          autoClose={5000}
          closeOnClick={true}
          theme="light"
        />   
      </body>
    </html>
  );
}
