import localFont from 'next/font/local'
import "./globals.css";
import Header from "@/components/header/Header";
import ReduxProvider from "@/redux/provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import QueryProvider from "@/providers/QueryProvider";

const futura = localFont({
  src: [
    {
      path: '../assets/fonts/FuturaStd-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/FuturaStd-Medium.woff2',
      weight: '500',
      style: 'semibold',
    },
    {
      path: '../assets/fonts/FuturaStd-Bold.woff2',
      weight: '700',
      style: 'bold',
    },
  ],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${futura.className} antialiased`}>
        <ReduxProvider>
          <QueryProvider> 
            <Header />
            {children}
          </QueryProvider>
        </ReduxProvider>
         <ToastContainer
          position="top-right"
          autoClose={5000}
          closeOnClick={true}
          theme="light"
        />   
      </body>
    </html>
  );
}
